#version: '3'
#services:
#  joviancareer-website-v2-flaskapp:
#    image: joviancareer-website-v2-flaskapp
#    ports:
#      - "5000:5000"
#    volumes:
#      - ssl_data:/etc/ssl/certs
#    env_file:
#      - ./.env
#volumes:
#  ssl_data:
