version: '3'

  
services:
  Prometheus:  
    image: jjjoh/joviancareerwebsitev2:prometheus-local
    ports:
      - '9090:9090'
  joviancareer-website-v2-flaskapp:
    #image: joviancareer-local-flaskapp
    image: joviancareer-website-v2-flaskapp-volumessl_data
    ports:
      - "5000:5000"
    volumes:
      - ssl_data:/etc/ssl/certs
    env_file:
      - ./.env
volumes:
  ssl_data:
