#Nom du fichier : docker-image.yml
#Version : 1-0-0
#Auteur : Johanne Schatz 
#Description : 
##Ce fichier de workflow GitHub Actions automatise la construction de l'image Docker et sa mise à disposition sur Docker Hub.
##Il définit un pipeline qui se déclenche à chaque push sur la branche main du dépôt. Lorsqu’il est déclenché, il construit une image Docker à partir du code source, ajoute comme tag son SHA de commit, puis la pousse vers le repo privé jjjoh/joviancareerwebsitev2 sur Docker Hub.

# Nom du workflow. Il s'affiche dans l'onglet Actions du dépôt GitHub.
name: Build and Push Docker Image

# Les événements qui déclenchent le workflow.
on:
  # Ce workflow se déclenche lors d'un push sur la branche 'main'.
  push:
    branches:
      - main

# Les jobs que le workflow va exécuter.
jobs:
  # Un job pour construire et pousser l'image Docker.
  build:
    # Le type de runner qui va exécuter ce job.
    runs-on: ubuntu-latest

    # Les étapes que le job va exécuter. 
    steps:   
    # Cette étape vérifie le code source du dépôt GitHub dans le runner.
    - name: Check Out Repo
      uses: actions/checkout@v2

    # Cette étape se connecte à Docker Hub en utilisant un nom d'utilisateur et un token d'accès.
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    # Cette étape récupère le hash de commit court du dernier commit sur la branche. 
    - name: Get short SHA # nom de l’étape, qui apparaîtra dans les logs de GitHub Actions.
      id: sha # identifiant de l’étape, utilisé pour référencer les résultats de cette étape dans d’autres parties du workflow.
      run: echo "::set-output name=sha::$(git rev-parse --short HEAD)" #commande exécutéee pendant cette étape. Elle utilise la commande git rev-parse --short HEAD pour obtenir le hash de commit court du dernier commit. Ensuite, elle utilise ::set-output name=sha:: pour enregistrer ce hash de commit comme une sortie de cette étape, qui peut être référencée plus tard dans le workflow en utilisant steps.sha.outputs.sha

    # Cette étape construit et pousse l'image Docker vers Docker Hub.
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        # Le contexte est le répertoire contenant le Dockerfile.
        context: .
        # Indique que l'image doit être poussée vers Docker Hub.
        push: true
        # Les tags de l'image Docker à pousser. Ici <nom d'utilisateur dockerhub>/<nom du repo>:<hash court du commit récupéré à l'étape "Get short SHA".
        tags: jjjoh/joviancareerwebsitev2:${{ steps.sha.outputs.sha }}
